name: Semantic version check

on:
  push:
    branches:
      - main

jobs:
  commit-message-check:
    if: ${{ startsWith(github.event.head_commit.message, 'major') ||
      startsWith(github.event.head_commit.message, 'minor') ||
      startsWith(github.event.head_commit.message, 'patch') }}
    uses: iam-medvedev/action-conventional-commit@v1.0.1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish-package:
    needs: commit-message-check
    uses: ./.github/workflows/publish-package.yml
    with:
      release-type: ${{ needs.commit-message-check.outputs.type }}
