# This is a basic workflow to help you get started with Actions

name: Semantic check

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  commit-message-check:
    if: ${{ startsWith(github.event.head_commit.message, 'major') ||
      startsWith(github.event.head_commit.message, 'minor') ||
      startsWith(github.event.head_commit.message, 'patch') }}
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.get-label.outputs.type }}
    steps:
      - name: Parse commit
        uses: iam-medvedev/action-conventional-commit@v1.0.1
        id: get-label
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-package:
    needs: commit-message-check
    uses: ./.github/workflows/publish-package.yml
    with:
      release-type: ${{ needs.commit-message-check.outputs.type }}
